spring:
  application:
    name: URL Shortener

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
#        hbm2ddl:
#          auto: create-drop

  mvc:
    hiddenmethod:
      filter:
        enabled: true

urls:
  ttl: 24h
  maxFollows: 10
